name: flutter_quiz
description: A new Flutter project.
publish_to: "none"
version: 0.1.2+3

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_database: ^10.1.2
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  flutter_localization: ^0.1.10
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  http: ^0.13.0
  intl: ^0.18.0
  introduction_screen: ^3.1.8
  responsive_framework: ^1.0.0
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.3.0

flutter_native_splash:
  android: true
  color: "#ffffff"
  image: "assets/icons/app-icon.png"

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
